### ISSUE TITLE
Can't create account with proposed email

### ISSUE THREAD

**Issue by Gorbunov-V** [robot-lab/tinkoff-web-service#103]
**Describe the bug**
Can't create account with proposed email

**To Reproduce**
1. Go to http://robotlab.apmath.spbu.ru:8013/register 
2. Enter email: gorbunov.v93@gmail.com
3. Fill all empty gaps correctly

**Expected behavior**
Created account

**Comment by danila19991** [comment]
Create user with such email.
![image](https://user-images.githubusercontent.com/21951917/44781112-2e93a800-ab8c-11e8-8555-19d7fb38590a.png)
